version: "3.9"
services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra-data:/var/lib/cassandra
    #restart: unless-stopped
  
volumes:
  cassandra-data:

